//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denemeportfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DbPortfolioEntities1 : DbContext
    {
        public DbPortfolioEntities1()
            : base("name=DbPortfolioEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal object GetLastProjectTitle()
        {
            throw new NotImplementedException();
        }

        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TblAbout> TblAbout { get; set; }
        public DbSet<TblAdress> TblAdress { get; set; }
        public DbSet<TblBanner> TblBanner { get; set; }
        public DbSet<TblCategory> TblCategory { get; set; }
        public DbSet<TblContact> TblContact { get; set; }
        public DbSet<TblFeature> TblFeature { get; set; }
        public DbSet<TblHobby> TblHobby { get; set; }
        public DbSet<TblProfile> TblProfile { get; set; }
        public DbSet<TblService> TblService { get; set; }
        public DbSet<TblSkill> TblSkill { get; set; }
        public DbSet<TblTestimonial> TblTestimonial { get; set; }
        public DbSet<TblProject> TblProject { get; set; }
    
        public virtual ObjectResult<string> GetLastSkillTitle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetLastSkillTitle");
        }
      

    }
}
