//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denemeportfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFeature
    {
        public int FeatureId { get; set; }
        public string FeatureTitle { get; set; }
        public string FeatureSubtitle { get; set; }
        public string FeatureImageUrl { get; set; }
    }
}
