//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denemeportfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSkill
    {
        public int SkillId { get; set; }
        public string Title { get; set; }
        public Nullable<byte> Value { get; set; }
        public Nullable<byte> LastWeekValue { get; set; }
        public Nullable<byte> LastMonthValue { get; set; }
    }
}
